export enum AdminAuthType {
  ADMIN_AUTH_SUCCESS = 'ADMIN_AUTH_SUCCESS',
  ADMIN_AUTH_REQUEST = 'ADMIN_AUTH_REQUEST',
  ADMIN_AUTH_FAIL = 'ADMIN_AUTH_FAIL',
}

export enum AdminSummaryType {
  ADMIN_FETCH_SUMMARY_DATA_SUCCESS = 'ADMIN_FETCH_SUMMARY_DATA_SUCCESS',
  ADMIN_FETCH_SUMMARY_DATA_REQUEST = 'ADMIN_FETCH_SUMMARY_DATA_REQUEST',
  ADMIN_FETCH_SUMMARY_DATA_FAIL = 'ADMIN_FETCH_SUMMARY_DATA_FAIL',
}
