export enum GETAllPlaceType {
  PLACE_FETCH_ALL_DATA_SUCCESS = 'PLACE_FETCH_ALL_DATA_SUCCESS',
  PLACE_FETCH_ALL_DATA_REQUEST = 'PLACE_FETCH_ALL_DATA_REQUEST',
  PLACE_FETCH_ALL_DATA_FAIL = 'PLACE_FETCH_ALL_DATA_FAIL',
}

export enum GETSinglePlaceType {
  PLACE_FETCH_SINGLE_DATA_SUCCESS = 'PLACE_FETCH_SINGLE_DATA_SUCCESS',
  PLACE_FETCH_SINGLE_DATA_REQUEST = 'PLACE_FETCH_SINGLE_DATA_REQUEST',
  PLACE_FETCH_SINGLE_DATA_FAIL = 'PLACE_FETCH_SINGLE_DATA_FAIL',
}
