export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS';
export const GET_SINGLE_USER_REQUEST = 'GET_SINGLE_USER_REQUEST';
export const GET_SINGLE_USER_FAIL = 'GET_SINGLE_USER_FAIL';

export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST';
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL';

export const CREATE_VACCINATED_USER_SUCCESS = 'CREATE_VACCINATED_USER_SUCCESS';
export const CREATE_VACCINATED_USER_REQUEST = 'CREATE_VACCINATED_USER_REQUEST';
export const CREATE_VACCINATED_USER_FAIL = 'CREATE_VACCINATED_USER_FAIL';
