// VACCINE

export const FETCH_VACCINE_SINGLE_DATA_SUCCESS =
  'FETCH_VACCINE_SINGLE_DATA_SUCCESS';
export const FETCH_VACCINE_SINGLE_DATA_REQUEST =
  'FETCH_VACCINE_SINGLE_DATA_REQUEST';
export const FETCH_VACCINE_SINGLE_DATA_FAIL = 'FETCH_VACCINE_SINGLE_DATA_FAIL';

export const FETCH_VACCINE_ALL_DATA_SUCCESS = 'FETCH_VACCINE_ALL_DATA_SUCCESS';
export const FETCH_VACCINE_ALL_DATA_REQUEST = 'FETCH_VACCINE_ALL_DATA_REQUEST';
export const FETCH_VACCINE_ALL_DATA_FAIL = 'FETCH_VACCINE_ALL_DATA_FAIL';

export const UPDATE_VACCINE_DATA_SUCCESS = 'UPDATE_VACCINE_DATA_SUCCESS';
export const UPDATE_VACCINE_DATA_REQUEST = 'UPDATE_VACCINE_DATA_REQUEST';
export const UPDATE_VACCINE_DATA_FAIL = 'UPDATE_VACCINE_DATA_FAIL';

export const DELETE_VACCINE_SUCCESS = 'DELETE_VACCINE_SUCCESS';
export const DELETE_VACCINE_REQUEST = 'DELETE_VACCINE_REQUEST';

// VACCINE LOTS

export const CREATE_VACCINE_LOTS_DATA_SUCCESS =
  'CREATE_VACCINE_LOTS_DATA_SUCCESS';
export const CREATE_VACCINE_LOTS_DATA_REQUEST =
  'CREATE_VACCINE_LOTS_DATA_REQUEST';
export const CREATE_VACCINE_LOTS_DATA_FAIL = 'CREATE_VACCINE_LOTS_DATA_FAIL';

export const DELETE_VACCINE_LOTS_SUCCESS = 'DELETE_VACCINE_LOTS_SUCCESS';
export const DELETE_VACCINE_LOTS_REQUEST = 'DELETE_VACCINE_LOTS_REQUEST';

export const UPDATE_VACCINE_LOTS_SUCCESS = 'UPDATE_VACCINE_LOTS_SUCCESS';
export const UPDATE_VACCINE_LOTS_REQUEST = 'UPDATE_VACCINE_LOTS_REQUEST';
export const UPDATE_VACCINE_LOTS_FAIL = 'UPDATE_VACCINE_LOTS_FAIL';
